
package com.jmp.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceStrImplService", targetNamespace = "http://ws.jmp.com/", wsdlLocation = "http://localhost:1986/wss/str?wsdl")
public class WebServiceStrImplService
    extends Service
{

    private final static URL WEBSERVICESTRIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICESTRIMPLSERVICE_EXCEPTION;
    private final static QName WEBSERVICESTRIMPLSERVICE_QNAME = new QName("http://ws.jmp.com/", "WebServiceStrImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1986/wss/str?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICESTRIMPLSERVICE_WSDL_LOCATION = url;
        WEBSERVICESTRIMPLSERVICE_EXCEPTION = e;
    }

    public WebServiceStrImplService() {
        super(__getWsdlLocation(), WEBSERVICESTRIMPLSERVICE_QNAME);
    }

    public WebServiceStrImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICESTRIMPLSERVICE_QNAME, features);
    }

    public WebServiceStrImplService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICESTRIMPLSERVICE_QNAME);
    }

    public WebServiceStrImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICESTRIMPLSERVICE_QNAME, features);
    }

    public WebServiceStrImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceStrImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceStr
     */
    @WebEndpoint(name = "WebServiceStrImplPort")
    public WebServiceStr getWebServiceStrImplPort() {
        return super.getPort(new QName("http://ws.jmp.com/", "WebServiceStrImplPort"), WebServiceStr.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceStr
     */
    @WebEndpoint(name = "WebServiceStrImplPort")
    public WebServiceStr getWebServiceStrImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.jmp.com/", "WebServiceStrImplPort"), WebServiceStr.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICESTRIMPLSERVICE_EXCEPTION!= null) {
            throw WEBSERVICESTRIMPLSERVICE_EXCEPTION;
        }
        return WEBSERVICESTRIMPLSERVICE_WSDL_LOCATION;
    }

}
